const characters = [
  { name: 'Michael Scott' },
  { name: 'Dwight Schrute' },
  { name: 'Jim Halpert' },
  { name: 'Pam Beesly' },
  { name: 'Ryan Howard' },
  { name: 'Andy Bernard' },
  { name: 'Angela Martin' },
  { name: 'Kevin Malone' },
  { name: 'Oscar Martinez' },
  { name: 'Stanley Hudson' },
  { name: 'Phyllis' },
  { name: 'Meredith Palmer' },
  { name: 'Toby Flenderson' },
  { name: 'Creed Bratton' },
  { name: 'Kelly Kapoor' },
  { name: 'Erin Hannon' },
  { name: 'Darryl Philbin' },
  { name: 'Jan Levinson' },
  { name: 'Holly Flax' },
  { name: 'Gabe Lewis' },
  { name: 'Roy Anderson' },
  { name: 'David Wallace' },
  { name: 'Karen Filippelli' },
  { name: 'Robert California' },
  { name: 'Nellie Bertram' },
  { name: 'Clark Green' },
  { name: 'Pete Miller' },
  { name: 'Deangelo Vickers' },
  { name: 'Charles Miner' },
  { name: 'Jo Bennett' },
  { name: 'Todd Packer' },
  { name: 'Rich Sommer' },
  { name: 'Billy Merchant' },
  { name: 'Nick' },
  { name: 'Devon White' },
  { name: 'Josh Porter' },
  { name: 'Hidetoshi Hasagawa' },
  { name: 'David Brent' },
  { name: 'Hank Tate' },
  { name: "Jim's Brothers" },
  { name: "Jim's Sister" },
  { name: 'Cathy Simms' },
  { name: 'Brian the Boom Guy' },
  { name: 'Mose Schrute' },
  { name: 'Zeke' },
  { name: 'Madge Madsen' },
  { name: 'Rolf' },
  { name: 'Elizabeth the Stripper' },
  { name: 'Frank the Warehouse Foreman' },
  { name: 'Val Johnson' },
  { name: 'Trevor' },
  { name: 'Martin Nash' },
  { name: 'Tony Gardner' },
  { name: "Pam's Grandmother" },
  { name: 'Brandon' },
  { name: 'Hunter' },
  { name: 'Carol Stills' },
  { name: 'Isabel Poreba' },
  { name: 'Senator Lipton' }
];

export default characters;
